package pl.edytab.automationorder.enums;

public enum ProductCategory {
    SENSOR, INVERTER, CONTROLLER, LIMIT_SWITCH, RELAY, ENCODER,
    REGULATOR, POWER_SUPPLY, COUNTER, CONNECTOR, CABLE, CONTACTOR,
    LICENSE, ROBOT, CAMERA
}
